'use strict';
const PROGRAMS={O0500:['메인 입력','치수·절삭조건·수량·3/4면취 모드 설정'],O9030:['전체 로직','진입 검사 → 원점 계산 → 준비 → 묶음·잔량 반복 → 종료'],O9031:['초기 준비','초기 황삭 → 마킹 → 단면가공. #122와 관계없이 처음 한 번 실행'],O9032:['묶음 선가공','황삭 선택과 3면취 선가공. 마지막 묶음도 #516으로 처리'],O9033:['3/4면취','3면취: 오른쪽 2곳 / 4면취: 오른쪽 → 내·외경 → 왼쪽 2곳'],O9034:['아래쪽 T2 절단','3면취: 왼쪽 외경 모따기 + 절단 / 4면취: 직선 절단']};
const VARS={
100:['자동 원점 길이','수량 × 피치 + 5. 기본 224.70. 입력란에서 246을 직접 넣는 방식이 아닙니다.'],
101:['소재 외경','기본 80. T2 접근·후퇴 기준.'],102:['소재 내경','기본 68. 단면 절삭 종료는 −(소재 내경−3.5).'],
103:['제품 외경','기본 74.90. T1은 양수 X, T2는 음수 X.'],104:['제품 내경','기본 70. 절단 끝은 X−65. T1 실제 내경은 복합 바이트 세팅·보정으로 확인.'],
105:['제품 길이','기본 15. 제품당 Z 길이.'],106:['T2 절단날 폭','기본 1.90. #105와 합산해 피치 계산.'],
107:['오른쪽 내경 모따기','기본 0.40. T1에서 사용.'],108:['오른쪽 외경 모따기','기본 0.40. T1에서 사용.'],109:['왼쪽 내경 모따기','기본 0.30. 4면취에서 T1이 가공하며 3면취에서는 사용하지 않습니다.'],110:['왼쪽 외경 모따기','기본 0.30. 3면취는 T2, 4면취는 T1이 가공.'],
111:['T1 황삭 이송','기본 0.15. #115를 곱한 분당 이송. 초기 황삭과 선택한 묶음 황삭에서 사용.'],112:['T1 내·외경 이송','기본 0.11. S1600에서 F176.'],113:['T1 모따기 이송','기본 0.15. S1600에서 F240.'],114:['T2 절단 이송','기본 0.09. S1600에서 F144.'],115:['T1 회전수','기본 1600 rpm.'],116:['T2 회전수','기본 1600 rpm.'],
120:['생산 수량','기본 13. 양의 정수. 완료 카운터로 정확히 종료.'],121:['면취 모드','기본 3면취. 3=오른쪽 내·외경 + 왼쪽 외경 / 4=양쪽 내·외경.'],122:['묶음 황삭','0=OFF, 1=ON. 초기 준비의 황삭·마킹은 그대로 실행.'],123:['묶음 수량','기본 3. 남은 수량보다 크면 실제 묶음 수량을 줄임.'],124:['짧은 소재 세팅','0=원점 길이 200 초과 검사, 1=그 검사만 생략. 종료 시 변수 0. 메인 입력문에 1이 남으면 재실행 때 다시 적용되므로 입력문도 복구.'],
147:['서브 호출 확인','호출 직전에 대상 번호를 넣고 해당 서브 첫머리에서 확인·소비.'],148:['입력 확인값','501만 O9030 진입 허용. 검사 통과 후 0.'],149:['O0500 입력 키','500. 입력 끝에서 #148=#149+1로 확인값 생성.'],
500:['완료 제품 누적 길이','#521 × #505. 실제 원점을 이동하는 값은 아닙니다.'],501:['T2 외측 접근 기준','#101+4. 기본 84 → X−84.'],502:['T2 단면 종료 기준','#102−3.5. 기본 64.5 → X−64.5.'],503:['T2 절단 외측 접근','#103+4. 기본 78.9 → X−78.9.'],504:['T2 절단 끝 기준','#104−5. 기본 65 → X−65.'],505:['제품당 피치','#105+#106. 기본 16.90.'],506:['설정 묶음 길이','#123×#505. 기본 50.70.'],509:['황삭 여유','1.0. T1 황삭 X=#103+1.'],510:['모따기 기준 여유','1.0. 오른쪽 모따기의 X/Z 계산 기준.'],
515:['실제 이번 묶음 수량','설정 묶음과 남은 수량 중 작은 값.'],516:['실제 이번 선가공 길이','#515×피치. 마지막 부족 묶음은 +0.5.'],517:['총 목표 수량','#120을 복사. 기본 13.'],518:['전체 제품 소모 길이','#517×#505. 기본 219.70.'],520:['묶음 내 완료 수량','묶음마다 0에서 시작, 절단 서브 복귀 후 증가.'],521:['전체 완료 수량','0부터 목표 수량까지 증가. 절단 서브 복귀 후 갱신.'],522:['전체 누적 Z 피치','모따기 전에는 완료 제품 길이, 절단 전에는 다음 절단 위치. 묶음마다 0으로 리셋하지 않습니다.'],530:['남은 제품 소모 길이','#531×#505. 척 안전거리 변수가 아닙니다.'],531:['묶음 시작 시 남은 제품 수','#517−#521. 묶음을 시작할 때 다시 계산합니다.'],532:['이번 묶음 선가공 길이 사본','#516의 기록값. 마지막 묶음 +0.5 포함.'],540:['5호기 보링 최대 길이','55. O2027 기준.'],541:['보링 여유 길이','1. 최대 유효 선가공 길이 54.'],542:['절단 끝 기준 여유','5. 원점 자동 계산에 더함. 실제 날끝·홀더 간격의 보증값이 아닙니다.'],543:['마지막 선가공 추가 길이','0.5. O0400의 잔량 여유. 마지막 선가공 끝은 절단 끝보다 0.5 깊을 수 있음.'],3000:['매크로 알람','번호와 메시지를 표시하고 정지. 진입·입력 검사는 G10과 이동 전에 수행.']};
const CODES={
G00:['급속 이동','다음 G01 전까지 급속 이동 모드 유지.'],G01:['직선 절삭','F 분당 이송으로 이동.'],G04:['드웰','P700은 O2027의 대기 지령을 따릅니다. 제어기의 실제 시간 단위는 실기 확인 대상.'],G10:['좌표 오프셋 입력','L2 P0 Z는 외부 워크 오프셋 절대값 설정. 이 프로그램은 시작과 종료에만 설정.'],G30:['기준점 복귀','O2027과 같은 U0 W0 지령. 실제 기준점은 기계 설정에 의존.'],G97:['고정 회전수','S는 rpm.'],G98:['분당 이송','mm 단위 기준 F=mm/min.'],
M00:['일시정지','초기 T2 Z0 위치에서 정지. 소재 세팅 후 재시작.'],M03:['5호기 주축 역회전','기존 김공장 5호기 M코드 표 기준.'],M05:['주축 정지','회전을 정지합니다.'],M12:['카운팅','각 제품의 절단·후퇴 뒤 1회.'],M30:['메인 종료','O0500 실행 종료.'],M51:['5호기 에어 ON','T2 절단 완료 블록.'],M52:['5호기 에어 OFF','T2 후퇴 블록.'],M53:['5호기 보링바 UP','3면취 묶음 선가공 또는 4면취 개별 내·외경 가공 전.'],M54:['5호기 보링바 DOWN','황삭 및 선가공 완료 후.'],M55:['5호기 면취 후진','초기 G30 블록에서 사용.'],M98:['서브 호출','초록색 P번호를 누르면 해당 서브로 이동.'],M99:['서브 복귀','호출한 프로그램의 다음 줄로 돌아갑니다.'],T01:['복합 보링바','위·아래 바이트로 내·외경 동시 가공.'],T02:['아래쪽 절단 바이트','X가 음수. 절댓값이 감소하는 방향으로 위쪽 절입.'],IF:['조건 검사','조건이 참이면 GOTO 실행.'],FIX:['정수부','양수의 소수 부분을 버립니다.'],EQ:['같다','='],NE:['다르다','≠'],LT:['미만','<'],LE:['이하','≤'],GT:['초과','>'],GE:['이상','≥']};
const NOTES={
'#100=#518+#542;':'선택한 원점 방식: 수량 × (제품 길이+날 폭) + 5. 기본 13×16.9+5=224.70.',
'#522=[#521+1]*#505;':'다음 절단 위치를 계산합니다. 첫 절단은 16.90, 마지막은 219.70. 실제 Z 지령에는 음수가 붙습니다.',
'#521=#521+1;':'절단 서브가 정상 복귀한 뒤 전체 완료 수량을 증가시킵니다.',
'#515=#531;':'남은 수량이 설정 묶음보다 작으면 이번 묶음을 남은 수량으로 줄입니다.',
'#516=#516+#543;':'마지막 부족 묶음은 O0400과 같이 선가공 깊이에 0.5를 더합니다. 유효 길이 54 검사를 적용합니다.',
'G01 U[#110*2.] W-[#110];':'아래쪽 T2의 3면취: U는 양수, W는 음수. 기본 U+0.6/W−0.3 → X−74.9에서 X−74.3으로 올라가며 모따기.',
'G01 X-[#504] M51;':'T2가 X−65까지 절입해 절단하고 에어를 켭니다. 같은 치수로 비교하면 O2027의 절단 지령과 일치합니다.',
'G00 X-[#101+10.];':'T2를 소재 바깥쪽 X−90으로 먼저 후퇴합니다. 이후 Z+10 후퇴.',
'G00 Z[-#522+20.];':'T1을 해당 제품/묶음 시작면 앞 20 mm로 후퇴합니다. 이 후퇴 후 T2로 전환합니다.',
'G00 U150;':'초기 G30 복귀 뒤 X방향 U+150 증분 이동. O2027 기준이며 실제 이동 반경은 지름 지령에서 75.',
'G00 Z[#505/3.];':'O0400의 초기 마킹 위치를 유지합니다. 기본 Z+5.6333. 원점 앞쪽의 초기 준비 구간.',
'G98 G01 Z-[#522+#105] F[#115*#112];':'4면취 모드에서 T1으로 제품 길이만큼 내·외경을 가공합니다. 첫 제품은 Z−15.',
'G01 X[#103-[#110*2.]] F[#115*#113];':'4면취 왼쪽 외경 모따기. 기본 X74.3, T1이 가공하므로 T2에서는 중복 모따기를 하지 않습니다.',
'G01 X[#103+[#109*2.]];':'4면취 왼쪽 내경 모따기. 기본 X75.5. 3면취 모드에서는 이 구간을 실행하지 않습니다.',
'G01 U0.2;':'G01을 명시한 T1 반경 0.1 이동. 직전 G00 모드에 영향을 받지 않도록 했습니다.',
'IF [#121 EQ 4] GOTO 33;':'4면취는 개별 제품의 O9033에서 내·외경을 가공하므로 묶음 정삭을 생략합니다. 선택한 묶음 황삭은 앞에서 실행됩니다.',
'G10 L2 P0 Z0.;':'G30 복귀 완료 후 외부 워크 Z 오프셋을 0으로 정리합니다.'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rawSource='';
const main=document.getElementById('main'), menu=document.getElementById('menuBtn'), sidebar=document.getElementById('sidebar'), backdrop=document.getElementById('backdrop'), tip=document.getElementById('tip');
const mobile=matchMedia('(max-width:760px)');
function drawer(open){sidebar.classList.toggle('open',open);backdrop.classList.toggle('show',open&&mobile.matches);menu.setAttribute('aria-expanded',String(open));sidebar.inert=mobile.matches&&!open;}
function route(){const [name,label]=location.hash.slice(1).split(':');const id=document.getElementById('page-'+name)?name:'overview';document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!=='page-'+id);document.querySelectorAll('#nav [data-page]').forEach(a=>{a.classList.toggle('active',a.dataset.page===id);if(a.dataset.page===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.scrollTop=0;drawer(false);tip.hidden=true;if(/^N\d+$/.test(label||'')){const el=document.getElementById('label-'+id+'-'+label);if(el){el.scrollIntoView({block:'center'});explain(el);}}}
menu.addEventListener('click',()=>drawer(!sidebar.classList.contains('open')));backdrop.addEventListener('click',()=>drawer(false));mobile.addEventListener('change',()=>drawer(false));window.addEventListener('hashchange',route);document.addEventListener('keydown',e=>{if(e.key==='Escape'){drawer(false);tip.hidden=true;}});document.getElementById('nav').addEventListener('click',e=>{const a=e.target.closest('[data-page]');if(a&&a.getAttribute('href')===location.hash){e.preventDefault();route();}});
function note(line){const trim=line.trim();if(NOTES[trim])return NOTES[trim];const set=trim.match(/^#(\d+)\s*=\s*(.*?);?$/);if(set){const v=VARS[set[1]];return '#'+set[1]+' '+(v?v[0]:'')+' ← '+set[2]+(v?' · '+v[1]:'');}if(/^IF/.test(trim))return '조건이 참이면 지정한 N번호로 이동합니다. 조건: '+trim;const parts=(trim.match(/\b(?:G\d+|M\d+|T\d+)\b/g)||[]).filter(c=>CODES[c]);return parts.length?parts.map(c=>c+' · '+CODES[c].join(' — ')).join(' / '):trim.replace(/[();]/g,'');}
function tokens(line,program){let result='',last=0;const re=/(\([^)]*\))|(#\d+)|(GOTO\s+\d+)|(M98\s+P\d+)|(\bN\d+\b)|(\b(?:G\d+|M\d+|T\d+|IF|FIX|EQ|NE|LT|LE|GT|GE)\b)/g;for(const m of line.matchAll(re)){result+=esc(line.slice(last,m.index));last=m.index+m[0].length;if(m[1])result+='<span class="cm">'+esc(m[0])+'</span>';else if(m[2])result+='<span class="var" data-var="'+m[0].slice(1)+'">'+m[0]+'</span>';else if(m[3]){const n=m[0].match(/\d+/)[0];result+='GOTO <a class="jump" href="#'+program+':N'+n+'">'+n+'</a>';}else if(m[4]){const n=m[0].match(/P(\d+)/)[1];result+='<span class="mc" data-code="M98">M98</span> <a class="jump" href="#O'+n.padStart(4,'0')+'">P'+n+'</a>';}else if(m[5])result+='<span class="label">'+m[0]+'</span>';else result+='<span class="'+(m[0].startsWith('M')?'mc':'gc')+'" data-code="'+m[0]+'">'+m[0]+'</span>';}return result+esc(line.slice(last));}
function render(program,source){const [title,desc]=PROGRAMS[program];const rows=source.split('\n').map((line,i)=>{const label=line.trim().match(/^N\d+/);return '<div class="ln'+(label?' block':'')+'" tabindex="0"'+(label?' id="label-'+program+'-'+label[0]+'"':'')+' data-line="'+(i+1)+'" data-note="'+esc(note(line))+'"><span class="gut" aria-hidden="true">'+(i+1)+'</span><span class="src">'+(tokens(line,program)||'&nbsp;')+'</span></div>';}).join('');document.getElementById('page-'+program).innerHTML='<h1>'+program+' · '+title+'</h1><div class="role">'+desc+'</div><div class="explain" role="status"><strong>코드 줄을 눌러 설명 보기</strong><span>변수·M코드 설명과 호출·GOTO 이동을 사용할 수 있습니다.</span></div><div class="actions"><a class="btn" href="programs/o0500/'+program+'.nc" download>'+program+' 개별 원문 받기</a><a class="btn" href="programs/o0500/'+program+'.txt" download>'+program+' TXT 받기</a></div><div class="codewrap"><div class="codehead">5호기 이식본 · 실기 검증 전 · 줄 번호는 해당 파일 기준</div><div class="code">'+rows+'</div></div>';}
function description(target){const el=target.closest('[data-var],[data-code]');if(!el)return null;if(el.dataset.var){const v=VARS[el.dataset.var];return v?['#'+el.dataset.var+' · '+v[0],v[1]]:null;}const c=CODES[el.dataset.code];return c?[el.dataset.code+' · '+c[0],c[1]]:null;}
function explain(target){const row=target.closest('.ln');if(!row)return;const page=row.closest('.page'),box=page.querySelector('.explain');page.querySelectorAll('.selected').forEach(el=>el.classList.remove('selected'));row.classList.add('selected');const desc=description(target);box.querySelector('strong').textContent=desc?desc[0]:'코드 '+row.dataset.line+'줄';box.querySelector('span').textContent=desc?desc[1]:row.dataset.note;}
main.addEventListener('click',e=>{if(!e.target.closest('a'))explain(e.target);});main.addEventListener('focusin',e=>{if(e.target.classList.contains('ln'))explain(e.target);});main.addEventListener('keydown',e=>{if(e.target.classList.contains('ln')&&['Enter',' '].includes(e.key)){e.preventDefault();explain(e.target);}});main.addEventListener('mousemove',e=>{if(mobile.matches)return;const desc=description(e.target);if(!desc){tip.hidden=true;return;}const strong=document.createElement('strong');strong.textContent=desc[0];tip.replaceChildren(strong,document.createTextNode(desc[1]));tip.hidden=false;const r=tip.getBoundingClientRect();tip.style.left=Math.max(12,Math.min(e.clientX+12,innerWidth-r.width-12))+'px';tip.style.top=Math.max(12,Math.min(e.clientY+14,innerHeight-r.height-12))+'px';});main.addEventListener('mouseleave',()=>tip.hidden=true);main.addEventListener('scroll',()=>tip.hidden=true,{passive:true});
function variables(){const q=document.getElementById('var-search').value.trim().toLowerCase();const entries=Object.entries(VARS).filter(([n,v])=>('#'+n+' '+v.join(' ')).toLowerCase().includes(q));document.getElementById('variable-rows').innerHTML=entries.map(([n,v])=>'<tr><td><code>#'+n+'</code></td><td>'+esc(v[0])+'</td><td>'+esc(v[1])+'</td></tr>').join('');document.getElementById('var-empty').hidden=entries.length>0;}
document.getElementById('var-search').addEventListener('input',variables);variables();
document.getElementById('copy-source').addEventListener('click',async()=>{const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(rawSource);status.textContent='6개 프로그램 전체를 복사했습니다.';}catch{status.textContent='원문 받기를 사용해 주세요.';}});
async function load(){try{const response=await fetch('programs/o0500-unit5.nc');if(!response.ok)throw Error('source');rawSource=await response.text();const blocks=rawSource.replace(/\r\n/g,'\n').split('%').map(s=>s.trim()).filter(Boolean);const seen=new Set();for(const block of blocks){const match=block.match(/^O\d+/);if(!match||!PROGRAMS[match[0]]||seen.has(match[0]))throw Error('program');seen.add(match[0]);render(match[0],'%\n'+block+'\n%');}if(seen.size!==6)throw Error('missing');document.getElementById('copy-source').disabled=false;route();}catch{for(const program of Object.keys(PROGRAMS))document.getElementById('page-'+program).innerHTML='<h1>'+program+'</h1><div class="check">원문을 불러오지 못했습니다. 연결 후 새로고침하거나 <a href="programs/o0500-unit5.nc">통합 파일</a>을 열어 주세요.</div>';}}
route();load();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
