'use strict';
const PROGRAMS={"O0600":["메인 입력","O8000 방식 입력 · T1 보링 / T2 면취 / T3 절단"],"O9050":["5호기 풀커팅 로직","입력 검사 → 준비 → 묶음 보링 → T2 면취 → T3 절단 → 잔량·종료"]};
const VARS={"100":["자동 원점","수량 × (제품 길이+날 폭) + 5. 기본 224.70."],"101":["소재 외경","기본 80. T3 외측 접근·후퇴 기준."],"102":["소재 내경","기본 68. 단면 끝은 X−64.5."],"103":["완성 외경","기본 74.90. T1 양수 X, T3/T2 음수 X."],"104":["완성 내경","기본 70. T3 절단 끝은 X−65."],"105":["제품 길이","기본 15."],"106":["T3 날 폭","기본 1.90. 피치는 길이+날 폭."],"107":["묶음 수량","기본 3. 남은 수량보다 크면 실제 묶음은 남은 수량으로 줄입니다. O0500의 오른쪽 내경 C가 아닙니다."],"108":["T1 보링 시작 rpm","기본 1600. 첫 묶음 회전수."],"109":["T1 보링 끝 rpm","기본 1600. 마지막 묶음 회전수."],"110":["T1 보링 이송","기본 0.11. F=#514×#110. 초기 황삭은 O8000처럼 0.15 사용."],"111":["T2 면취 시작 rpm","기본 1600. 첫 제품 면취 회전수."],"112":["T2 면취 끝 rpm","기본 1600. 마지막 제품 면취 회전수."],"113":["T2 면취 이송","기본 0.09. F=#515×#113."],"114":["T3 절단 시작 rpm","기본 1600. 초기 마킹·단면과 첫 절단."],"115":["T3 절단 끝 rpm","기본 1600. 마지막 절단 회전수."],"116":["T3 절단 이송","기본 0.09. F=#516×#116."],"117":["소재 길이 세팅","0 기본 / 1이면 T3 X−(소재 OD+50), Z=날 폭+1.5에서 추가 M00."],"118":["제품별 후퇴","0 기본 / 1이면 각 제품 후 G30 U0 W0 → U150. 6호기 P3 후퇴를 그대로 사용하지 않습니다."],"119":["뒤쪽 외경 면취 C","기본 0.55. T3 U+1.10 / W−0.55."],"120":["목표 수량","기본 13. 양의 정수."],"121":["짧은 소재 세팅","0 기본 / 1이면 200 mm 길이 검사만 생략. O0500의 3/4면취 선택 변수가 아닙니다."],"122":["초기 황삭·마킹 생략","0 기본 / 1이면 N203 단면부터 실행. 단면은 항상 가공. O0500의 묶음 황삭 선택이 아닙니다."],"126":["시스템 카운터 검사","0 기본. 5호기 #3901/#3902 지원과 M12 연동 확인 후 1로 사용."],"148":["입력 확인값","8501만 O9050 진입 허용. 통과 후 0."],"149":["진입 키","8500. O0500의 500과 구분."],"500":["완료 길이","전체 완료 수량 #523 × 피치."],"501":["T3 소재 외측","소재 OD+4. 기본 X−84."],"502":["T3 단면 끝","소재 ID−3.5. 기본 X−64.5."],"503":["T3 절단 접근","완성 OD+4. 기본 X−78.9."],"504":["T3 절단 끝","완성 ID−5. 기본 X−65."],"505":["피치","제품 길이+날 폭. 기본 16.90."],"506":["설정 묶음 길이","#107×피치. 기본 50.70."],"507":["이번 선가공 길이","실제 묶음 길이+0.50. 기본 정상 51.20, 마지막 17.40."],"508":["T2 면취 중심 직경","(완성 OD+ID)/2. 기본 72.45 → X−72.45. 실제 면취기는 T2 보정과 형상 확인."],"511":["T1 묶음별 rpm 증분","실제 묶음 수−1로 계산. 1묶음이면 0."],"512":["T2 제품별 rpm 증분","실제 수량−1로 계산. 1개면 0."],"513":["T3 제품별 rpm 증분","실제 수량−1로 계산. 1개면 0."],"514":["현재 T1 rpm","#108+#511×완료 묶음 수."],"515":["현재 T2 rpm","#111+#512×전체 완료 수량."],"516":["현재 T3 rpm","#114+#513×전체 완료 수량."],"517":["총 목표 수량","#120을 복사."],"518":["총 소모 길이","목표 수량×피치. 기본 219.70."],"520":["이번 묶음 완료 수","묶음마다 0부터 시작."],"521":["묶음 내 면취 위치","현재 워크 원점에서 제품 앞면까지의 누적 피치."],"522":["묶음 내 절단 위치","현재 워크 원점에서 절단면까지의 누적 피치."],"523":["전체 완료 수","M12 후 증가. 지정 수량 종료 기준."],"524":["이번 묶음 수량","설정 묶음과 잔량 중 작은 값."],"525":["완료 묶음 수","첫 묶음에서 0. T1 rpm 계산 기준."],"530":["남은 소모 길이","남은 수량×피치. 원점 여유 5 mm는 포함하지 않습니다."],"531":["남은 수량","전체 목표−전체 완료."],"532":["이번 묶음 소모 길이","실제 묶음 수×피치. 다음 묶음 G10 W 이동량."],"534":["전체 묶음 수","총 수량을 묶음 수량으로 나눈 올림값."],"540":["보링 최대 길이","55. O2027 참고값."],"541":["보링 여유 길이","1. 최대 유효 선가공 길이 54."],"542":["절단 끝 기준 여유","5. 자동 원점에 더함. 홀더와 척의 실제 간격 보증값이 아닙니다."],"543":["선가공 추가 길이","0.5. 정상·잔량 묶음 모두 적용."],"3000":["매크로 알람","입력·진입·시스템 카운터 검사 시 정지."],"3901":["시스템 완료 카운터","#126=1에서만 사용. 5호기 변수 지원 및 M12 연동 확인 필요."],"3902":["시스템 목표 카운터","#126=1에서만 사용. 목표 0 이하면 알람 27."]};
const CODES={"G00":["급속 이동","다음 G01 전까지 급속 이동 모드 유지."],"G01":["직선 절삭","F 분당 이송으로 절삭."],"G04":["드웰","P700은 O2027의 보링바 대기 지령."],"G10":["워크 오프셋","Z는 절대 설정, W는 현재 오프셋에서 증분 이동. 묶음마다 W−이번 묶음 길이."],"G30":["5호기 기준점 복귀","U0 W0 지령. 실제 위치는 5호기 기준점 설정에 따름."],"G97":["고정 회전수","S는 rpm."],"G98":["분당 이송","F=rpm×입력 이송."],"M00":["일시정지","소재 세팅 후 작업자가 재시작."],"M01":["선택 정지","장비의 선택 정지 스위치가 켜진 경우 정지."],"M03":["5호기 역회전","5호기 표 기준. 6호기 M03 정회전과 기계 방향이 다릅니다."],"M05":["주축 정지","가공 종료 때 주축 정지."],"M12":["제품 카운팅","제품별 절단·후퇴 후 한 번."],"M30":["메인 종료","O0600 종료."],"M51":["에어 ON","5호기 에어 ON."],"M52":["에어 OFF","5호기 에어 OFF."],"M53":["보링바 UP","5호기 보링바 UP."],"M54":["보링바 DOWN","5호기 보링바 DOWN."],"M55":["면취기 후진","T2 면취 후 후진."],"M56":["면취기 전진","T2 면취 위치에서 전진."],"M98":["서브 호출","M98 P9050으로 가공 로직 호출."],"M99":["서브 복귀","O0600으로 복귀."],"T01":["복합 보링바","내·외경 묶음 선가공."],"T03":["아래쪽 절단","음수 X에서 위로 절입."],"T02":["면취기","변경된 배치의 T02 면취기. M56 전진 / M55 후진."],"IF":["조건 검사","참이면 지정 라벨로 이동."],"FIX":["정수부","양수의 소수 부분을 버림."],"EQ":["같음","="],"NE":["다름","≠"],"LT":["미만","<"],"LE":["이하","≤"],"GT":["초과",">"],"GE":["이상","≥"]};
const NOTES={"#100=#518+#542;":"자동 원점: 13×16.90+5=224.70.","#507=#532+#543;":"정상 묶음과 잔량 모두 실제 소모 길이에 0.5를 더해 선가공합니다.","G10 L2 P0 W-[#532];":"묶음 가공 완료 후 해당 묶음 길이만큼 워크 원점을 이동합니다. 기본 50.70씩 이동.","G97 G00 X-[#508] S#515 M03 T02;":"T2 면취기를 X−72.45 중심 직경으로 이동. 변경된 5호기 배치에서 T02가 면취를 담당합니다.","G00 Z[2.-#521] M56;":"이번 제품 앞면 2 mm 앞에 접근하며 면취기를 전진합니다.","G98 G01 Z-[#521] F[#515*#113];":"T2 면취기 전용 공구로 앞쪽 면취. 실제 C값은 면취기의 날 형상·보정에 따릅니다.","G00 W10. M55;":"면취 위치에서 Z+10 후퇴하고 M55로 면취기를 복귀합니다. #521/#516/#522 계산은 이 줄 전에 완료하며, 이후 M01을 거쳐 T3 이동으로 이어집니다.","G01 U[#119*2.] W-[#119];":"T3 뒤쪽 외경 면취. 기본 U+1.10 / W−0.55로 아래에서 위로 절입.","G01 X-[#504] M51;":"X−65까지 절입하여 제품 절단, 에어 ON. 5호기 기준 완성 ID−5 적용.","G00 W[#505+20.] M52;":"T3를 앞쪽으로 피치+20 후퇴하며 에어 OFF. 다음 공구 전환 공간 확보.","G00 U150;":"5호기 O2027의 기준점 복귀 후 U+150 이동. 실제 기준점과 이동 여유는 장비에서 확인.","IF [#122 EQ 1] GOTO 203;":"마킹 생략이면 초기 황삭과 마킹을 건너뛰고 단면을 실행합니다.","#523=#523+1;":"절단과 M12 이후 전체 완료 수량 증가. 5 mm 여유가 제품 수량에 포함되지 않게 합니다."};
NOTES['G00 Z5. M52;']='O8000과 같은 페이스 후 Z5 후퇴. 다음 T1 선택 뒤 Z2로 직접 접근합니다.';
NOTES['G97 G00 X#103 S#514 M03 T01;']='O8000처럼 T1의 X 위치와 회전수를 함께 지정합니다. 진입부의 Z20 경유를 삭제했습니다.';
NOTES['G00 Z2. M53;']='T1을 Z2로 직접 접근하며 5호기 M53으로 보링바를 UP합니다.';
NOTES['G97 G00 X-[#503] S#516 M03 T03;']='미리 계산한 절단 회전수로 T3를 X 외측에 맞춥니다. G97/S/M03을 첫 X 이동에 함께 지정합니다.';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rawSource='';
const main=document.getElementById('main'), menu=document.getElementById('menuBtn'), sidebar=document.getElementById('sidebar'), backdrop=document.getElementById('backdrop'), tip=document.getElementById('tip');
const mobile=matchMedia('(max-width:760px)');
function drawer(open){sidebar.classList.toggle('open',open);backdrop.classList.toggle('show',open&&mobile.matches);menu.setAttribute('aria-expanded',String(open));sidebar.inert=mobile.matches&&!open;}
function route(){const [name,label]=location.hash.slice(1).split(':');const id=document.getElementById('page-'+name)?name:'overview';document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!=='page-'+id);document.querySelectorAll('#nav [data-page]').forEach(a=>{a.classList.toggle('active',a.dataset.page===id);if(a.dataset.page===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.scrollTop=0;drawer(false);tip.hidden=true;if(/^N\d+$/.test(label||'')){const el=document.getElementById('label-'+id+'-'+label);if(el){el.scrollIntoView({block:'center'});explain(el);}}}
menu.addEventListener('click',()=>drawer(!sidebar.classList.contains('open')));backdrop.addEventListener('click',()=>drawer(false));mobile.addEventListener('change',()=>drawer(false));window.addEventListener('hashchange',route);document.addEventListener('keydown',e=>{if(e.key==='Escape'){drawer(false);tip.hidden=true;}});document.getElementById('nav').addEventListener('click',e=>{const a=e.target.closest('[data-page]');if(a&&a.getAttribute('href')===location.hash){e.preventDefault();route();}});
function note(line){const trim=line.trim();if(NOTES[trim])return NOTES[trim];const set=trim.match(/^#(\d+)\s*=\s*(.*?);?$/);if(set){const v=VARS[set[1]];return '#'+set[1]+' '+(v?v[0]:'')+' ← '+set[2]+(v?' · '+v[1]:'');}if(/^IF/.test(trim))return '조건이 참이면 지정한 N번호로 이동합니다. 조건: '+trim;const parts=(trim.match(/\b(?:G\d+|M\d+|T\d+)\b/g)||[]).filter(c=>CODES[c]);return parts.length?parts.map(c=>c+' · '+CODES[c].join(' — ')).join(' / '):trim.replace(/[();]/g,'');}
function tokens(line,program){let result='',last=0;const re=/(\([^)]*\))|(#\d+)|(GOTO\s+\d+)|(M98\s+P\d+)|(\bN\d+\b)|(\b(?:G\d+|M\d+|T\d+|IF|FIX|EQ|NE|LT|LE|GT|GE)\b)/g;for(const m of line.matchAll(re)){result+=esc(line.slice(last,m.index));last=m.index+m[0].length;if(m[1])result+='<span class="cm">'+esc(m[0])+'</span>';else if(m[2])result+='<span class="var" data-var="'+m[0].slice(1)+'">'+m[0]+'</span>';else if(m[3]){const n=m[0].match(/\d+/)[0];result+='GOTO <a class="jump" href="#'+program+':N'+n+'">'+n+'</a>';}else if(m[4]){const n=m[0].match(/P(\d+)/)[1];result+='<span class="mc" data-code="M98">M98</span> <a class="jump" href="#O'+n.padStart(4,'0')+'">P'+n+'</a>';}else if(m[5])result+='<span class="label">'+m[0]+'</span>';else result+='<span class="'+(m[0].startsWith('M')?'mc':'gc')+'" data-code="'+m[0]+'">'+m[0]+'</span>';}return result+esc(line.slice(last));}
function render(program,source){const [title,desc]=PROGRAMS[program];const rows=source.split('\n').map((line,i)=>{const label=line.trim().match(/^N\d+/);return '<div class="ln'+(label?' block':'')+'" tabindex="0"'+(label?' id="label-'+program+'-'+label[0]+'"':'')+' data-line="'+(i+1)+'" data-note="'+esc(note(line))+'"><span class="gut" aria-hidden="true">'+(i+1)+'</span><span class="src">'+(tokens(line,program)||'&nbsp;')+'</span></div>';}).join('');document.getElementById('page-'+program).innerHTML='<h1>'+program+' · '+title+'</h1><div class="role">'+desc+'</div><div class="explain" role="status"><strong>코드 줄을 눌러 설명 보기</strong><span>변수·M코드 설명과 호출·GOTO 이동을 사용할 수 있습니다.</span></div><div class="actions"><a class="btn" href="programs/o0600/'+program+'.nc" download>'+program+' NC</a><a class="btn" href="programs/o0600/'+program+'.txt" download>'+program+' TXT</a></div><div class="codewrap"><div class="codehead">5호기 이식본 · 실기 검증 전 · 줄 번호는 해당 파일 기준</div><div class="code">'+rows+'</div></div>';}
function description(target){const el=target.closest('[data-var],[data-code]');if(!el)return null;if(el.dataset.var){const v=VARS[el.dataset.var];return v?['#'+el.dataset.var+' · '+v[0],v[1]]:null;}const c=CODES[el.dataset.code];return c?[el.dataset.code+' · '+c[0],c[1]]:null;}
function explain(target){const row=target.closest('.ln');if(!row)return;const page=row.closest('.page'),box=page.querySelector('.explain');page.querySelectorAll('.selected').forEach(el=>el.classList.remove('selected'));row.classList.add('selected');const desc=description(target);box.querySelector('strong').textContent=desc?desc[0]:'코드 '+row.dataset.line+'줄';box.querySelector('span').textContent=desc?desc[1]:row.dataset.note;}
main.addEventListener('click',e=>{if(!e.target.closest('a'))explain(e.target);});main.addEventListener('focusin',e=>{if(e.target.classList.contains('ln'))explain(e.target);});main.addEventListener('keydown',e=>{if(e.target.classList.contains('ln')&&['Enter',' '].includes(e.key)){e.preventDefault();explain(e.target);}});main.addEventListener('mousemove',e=>{if(mobile.matches)return;const desc=description(e.target);if(!desc){tip.hidden=true;return;}const strong=document.createElement('strong');strong.textContent=desc[0];tip.replaceChildren(strong,document.createTextNode(desc[1]));tip.hidden=false;const r=tip.getBoundingClientRect();tip.style.left=Math.max(12,Math.min(e.clientX+12,innerWidth-r.width-12))+'px';tip.style.top=Math.max(12,Math.min(e.clientY+14,innerHeight-r.height-12))+'px';});main.addEventListener('mouseleave',()=>tip.hidden=true);main.addEventListener('scroll',()=>tip.hidden=true,{passive:true});
function variables(){const q=document.getElementById('var-search').value.trim().toLowerCase();const entries=Object.entries(VARS).filter(([n,v])=>('#'+n+' '+v.join(' ')).toLowerCase().includes(q));document.getElementById('variable-rows').innerHTML=entries.map(([n,v])=>'<tr><td><code>#'+n+'</code></td><td>'+esc(v[0])+'</td><td>'+esc(v[1])+'</td></tr>').join('');document.getElementById('var-empty').hidden=entries.length>0;}
document.getElementById('var-search').addEventListener('input',variables);variables();
document.getElementById('copy-source').addEventListener('click',async()=>{const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(rawSource);status.textContent='2개 프로그램 전체를 복사했습니다.';}catch{status.textContent='원문 받기를 사용해 주세요.';}});
async function load(){try{const response=await fetch('programs/o0600-unit5.nc');if(!response.ok)throw Error('source');rawSource=await response.text();const blocks=rawSource.replace(/\r\n/g,'\n').split('%').map(s=>s.trim()).filter(Boolean);const seen=new Set();for(const block of blocks){const match=block.match(/^O\d+/);if(!match||!PROGRAMS[match[0]]||seen.has(match[0]))throw Error('program');seen.add(match[0]);render(match[0],'%\n'+block+'\n%');}if(seen.size!==2)throw Error('missing');document.getElementById('copy-source').disabled=false;route();}catch{for(const program of Object.keys(PROGRAMS))document.getElementById('page-'+program).innerHTML='<h1>'+program+'</h1><div class="check">원문을 불러오지 못했습니다. 연결 후 새로고침하거나 <a href="programs/o0600-unit5.nc">통합 파일</a>을 열어 주세요.</div>';}}
route();load();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
